<div class="container text-center">
    <form class='form-generate' onsubmit="App.generateShortUrlHandler(event, this)">
        <h1 class='h3 mb-3 font-weight-normal'>Generate short URL</h1>

        <input type='text'
               id='url'
               name='url'
               class='form-control mb-3'
               placeholder='Enter address'
               required
               autofocus
               onclick="App.selectText(this)"
        />

        <button class='btn btn-lg btn-primary btn-block'
                type='submit'
        >Go!
        </button>

    </form>
</div>

<div id="modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="modal-message"></p>
                <form id="modal-form" class="hidden">
                    <div class="form-group">
                        <input type="text"
                               id="modal-input"
                               class="form-control"
                               value=""
                               title="Short Url"
                               onclick="App.selectText(this)"
                        />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button"
                        id="modal-copy"
                        class="btn btn-info hidden"
                        title="Copy"
                        onclick="App.copyToClipboard($('#modal-input'), this)">
                    Copy
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
