<!doctype html>
<html xml:lang="ru" lang="ru">
<head>
    <meta charset="utf-8">
    <title>Test <?= !empty($title) ? " — " . $title : "" ?></title>
    <link rel="icon" type="image/png" href="/favicon.png"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link rel="stylesheet" href="/assets/styles/app.css">
</head>
<body>